// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package integration.framework.openlaw.ExternalService

object ExternalServiceProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      integration.framework.openlaw.ExternalService.EthereumAddressResponse,
      integration.framework.openlaw.ExternalService.MarkupInterfaceResponse,
      integration.framework.openlaw.ExternalService.ExecuteRequest,
      integration.framework.openlaw.ExternalService.ExecuteResponse,
      integration.framework.openlaw.ExternalService.Empty
    )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """ChVFeHRlcm5hbFNlcnZpY2UucHJvdG8SHWludGVncmF0aW9uLmZyYW1ld29yay5vcGVubGF3IkEKF0V0aGVyZXVtQWRkcmVzc
  1Jlc3BvbnNlEiYKB2FkZHJlc3MYASABKAlCDOI/CRIHYWRkcmVzc1IHYWRkcmVzcyJKChdNYXJrdXBJbnRlcmZhY2VSZXNwb25zZ
  RIvCgpkZWZpbml0aW9uGAEgASgJQg/iPwwSCmRlZmluaXRpb25SCmRlZmluaXRpb24ikQIKDkV4ZWN1dGVSZXF1ZXN0EikKCGNhb
  GxlcklkGAEgASgJQg3iPwoSCGNhbGxlcklkUghjYWxsZXJJZBIpCghhY3Rpb25JZBgCIAEoCUIN4j8KEghhY3Rpb25JZFIIYWN0a
  W9uSWQSLAoJcmVxdWVzdElkGAMgASgJQg7iPwsSCXJlcXVlc3RJZFIJcmVxdWVzdElkEiwKCWlucHV0SnNvbhgEIAEoCUIO4j8LE
  glpbnB1dEpzb25SCWlucHV0SnNvbhJNChRzZXJ2aWNlUHVibGljQWRkcmVzcxgFIAEoCUIZ4j8WEhRzZXJ2aWNlUHVibGljQWRkc
  mVzc1IUc2VydmljZVB1YmxpY0FkZHJlc3Mi/QMKD0V4ZWN1dGVSZXNwb25zZRIpCghjYWxsZXJJZBgBIAEoCUIN4j8KEghjYWxsZ
  XJJZFIIY2FsbGVySWQSKQoIYWN0aW9uSWQYAiABKAlCDeI/ChIIYWN0aW9uSWRSCGFjdGlvbklkEiwKCXJlcXVlc3RJZBgDIAEoC
  UIO4j8LEglyZXF1ZXN0SWRSCXJlcXVlc3RJZBIvCgpvdXRwdXRKc29uGAQgASgJQg/iPwwSCm91dHB1dEpzb25SCm91dHB1dEpzb
  24SPgoPb3V0cHV0U2lnbmF0dXJlGAUgASgJQhTiPxESD291dHB1dFNpZ25hdHVyZVIPb3V0cHV0U2lnbmF0dXJlEloKBnN0YXR1c
  xgGIAEoDjI1LmludGVncmF0aW9uLmZyYW1ld29yay5vcGVubGF3LkV4ZWN1dGVSZXNwb25zZS5TdGF0dXNCC+I/CBIGc3RhdHVzU
  gZzdGF0dXMSJgoHbWVzc2FnZRgHIAEoCUIM4j8JEgdtZXNzYWdlUgdtZXNzYWdlEk0KFHNlcnZpY2VQdWJsaWNBZGRyZXNzGAggA
  SgJQhniPxYSFHNlcnZpY2VQdWJsaWNBZGRyZXNzUhRzZXJ2aWNlUHVibGljQWRkcmVzcyIiCgZTdGF0dXMSCwoHRkFJTFVSRRAAE
  gsKB1NVQ0NFU1MQASIHCgVFbXB0eTLpAgoPRXh0ZXJuYWxTZXJ2aWNlEnQKEkdldEV0aGVyZXVtQWRkcmVzcxIkLmludGVncmF0a
  W9uLmZyYW1ld29yay5vcGVubGF3LkVtcHR5GjYuaW50ZWdyYXRpb24uZnJhbWV3b3JrLm9wZW5sYXcuRXRoZXJldW1BZGRyZXNzU
  mVzcG9uc2UiABJ0ChJHZXRNYXJrdXBJbnRlcmZhY2USJC5pbnRlZ3JhdGlvbi5mcmFtZXdvcmsub3Blbmxhdy5FbXB0eRo2Lmlud
  GVncmF0aW9uLmZyYW1ld29yay5vcGVubGF3Lk1hcmt1cEludGVyZmFjZVJlc3BvbnNlIgASagoHRXhlY3V0ZRItLmludGVncmF0a
  W9uLmZyYW1ld29yay5vcGVubGF3LkV4ZWN1dGVSZXF1ZXN0Gi4uaW50ZWdyYXRpb24uZnJhbWV3b3JrLm9wZW5sYXcuRXhlY3V0Z
  VJlc3BvbnNlIgBiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}