// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package integration.framework.openlaw

object ExternalServiceProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      integration.framework.openlaw.EthereumAddressResponse,
      integration.framework.openlaw.MarkupInterfaceResponse,
      integration.framework.openlaw.ExecuteRequest,
      integration.framework.openlaw.ExecuteResponse,
      integration.framework.openlaw.Empty
    )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """ChVFeHRlcm5hbFNlcnZpY2UucHJvdG8SHWludGVncmF0aW9uLmZyYW1ld29yay5vcGVubGF3IkEKF0V0aGVyZXVtQWRkcmVzc
  1Jlc3BvbnNlEiYKB2FkZHJlc3MYASABKAlCDOI/CRIHYWRkcmVzc1IHYWRkcmVzcyJKChdNYXJrdXBJbnRlcmZhY2VSZXNwb25zZ
  RIvCgpkZWZpbml0aW9uGAEgASgJQg/iPwwSCmRlZmluaXRpb25SCmRlZmluaXRpb24ikQIKDkV4ZWN1dGVSZXF1ZXN0EikKCGNhb
  GxlcklkGAEgASgJQg3iPwoSCGNhbGxlcklkUghjYWxsZXJJZBIpCghhY3Rpb25JZBgCIAEoCUIN4j8KEghhY3Rpb25JZFIIYWN0a
  W9uSWQSLAoJcmVxdWVzdElkGAMgASgJQg7iPwsSCXJlcXVlc3RJZFIJcmVxdWVzdElkEiwKCWlucHV0SnNvbhgEIAEoCUIO4j8LE
  glpbnB1dEpzb25SCWlucHV0SnNvbhJNChRzZXJ2aWNlUHVibGljQWRkcmVzcxgFIAEoCUIZ4j8WEhRzZXJ2aWNlUHVibGljQWRkc
  mVzc1IUc2VydmljZVB1YmxpY0FkZHJlc3MirgQKD0V4ZWN1dGVSZXNwb25zZRIpCghjYWxsZXJJZBgBIAEoCUIN4j8KEghjYWxsZ
  XJJZFIIY2FsbGVySWQSKQoIYWN0aW9uSWQYAiABKAlCDeI/ChIIYWN0aW9uSWRSCGFjdGlvbklkEiwKCXJlcXVlc3RJZBgDIAEoC
  UIO4j8LEglyZXF1ZXN0SWRSCXJlcXVlc3RJZBIvCgpvdXRwdXRKc29uGAQgASgJQg/iPwwSCm91dHB1dEpzb25SCm91dHB1dEpzb
  24SPgoPb3V0cHV0U2lnbmF0dXJlGAUgASgJQhTiPxESD291dHB1dFNpZ25hdHVyZVIPb3V0cHV0U2lnbmF0dXJlEloKBnN0YXR1c
  xgGIAEoDjI1LmludGVncmF0aW9uLmZyYW1ld29yay5vcGVubGF3LkV4ZWN1dGVSZXNwb25zZS5TdGF0dXNCC+I/CBIGc3RhdHVzU
  gZzdGF0dXMSJgoHbWVzc2FnZRgHIAEoCUIM4j8JEgdtZXNzYWdlUgdtZXNzYWdlEk0KFHNlcnZpY2VQdWJsaWNBZGRyZXNzGAggA
  SgJQhniPxYSFHNlcnZpY2VQdWJsaWNBZGRyZXNzUhRzZXJ2aWNlUHVibGljQWRkcmVzcxIvCgpzdGF0dXNDb2RlGAkgASgNQg/iP
  wwSCnN0YXR1c0NvZGVSCnN0YXR1c0NvZGUiIgoGU3RhdHVzEgsKB0ZBSUxVUkUQABILCgdTVUNDRVNTEAEiBwoFRW1wdHky6QIKD
  0V4dGVybmFsU2VydmljZRJ0ChJHZXRFdGhlcmV1bUFkZHJlc3MSJC5pbnRlZ3JhdGlvbi5mcmFtZXdvcmsub3Blbmxhdy5FbXB0e
  Ro2LmludGVncmF0aW9uLmZyYW1ld29yay5vcGVubGF3LkV0aGVyZXVtQWRkcmVzc1Jlc3BvbnNlIgASdAoSR2V0TWFya3VwSW50Z
  XJmYWNlEiQuaW50ZWdyYXRpb24uZnJhbWV3b3JrLm9wZW5sYXcuRW1wdHkaNi5pbnRlZ3JhdGlvbi5mcmFtZXdvcmsub3Blbmxhd
  y5NYXJrdXBJbnRlcmZhY2VSZXNwb25zZSIAEmoKB0V4ZWN1dGUSLS5pbnRlZ3JhdGlvbi5mcmFtZXdvcmsub3Blbmxhdy5FeGVjd
  XRlUmVxdWVzdBouLmludGVncmF0aW9uLmZyYW1ld29yay5vcGVubGF3LkV4ZWN1dGVSZXNwb25zZSIAYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}