// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package integration.framework.openlaw

/** The Markup Interface response message.
  *
  * @param definition
  *   The Markup Interface definition that matches the 
  *   OpenLaw Input/Output structures.
  */
@SerialVersionUID(0L)
final case class MarkupInterfaceResponse(
    definition: _root_.scala.Predef.String = ""
    ) extends scalapb.GeneratedMessage with scalapb.Message[MarkupInterfaceResponse] with scalapb.lenses.Updatable[MarkupInterfaceResponse] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = definition
        if (__value != "") {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      __size
    }
    final override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = definition
        if (__v != "") {
          _output__.writeString(1, __v)
        }
      };
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): integration.framework.openlaw.MarkupInterfaceResponse = {
      var __definition = this.definition
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __definition = _input__.readString()
          case tag => _input__.skipField(tag)
        }
      }
      integration.framework.openlaw.MarkupInterfaceResponse(
          definition = __definition
      )
    }
    def withDefinition(__v: _root_.scala.Predef.String): MarkupInterfaceResponse = copy(definition = __v)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = definition
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(definition)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = integration.framework.openlaw.MarkupInterfaceResponse
}

object MarkupInterfaceResponse extends scalapb.GeneratedMessageCompanion[integration.framework.openlaw.MarkupInterfaceResponse] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[integration.framework.openlaw.MarkupInterfaceResponse] = this
  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, _root_.scala.Any]): integration.framework.openlaw.MarkupInterfaceResponse = {
    _root_.scala.Predef.require(__fieldsMap.keys.forall(_.getContainingType() == javaDescriptor), "FieldDescriptor does not match message type.")
    val __fields = javaDescriptor.getFields
    integration.framework.openlaw.MarkupInterfaceResponse(
      __fieldsMap.getOrElse(__fields.get(0), "").asInstanceOf[_root_.scala.Predef.String]
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[integration.framework.openlaw.MarkupInterfaceResponse] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      integration.framework.openlaw.MarkupInterfaceResponse(
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = ExternalServiceProto.javaDescriptor.getMessageTypes.get(1)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = ExternalServiceProto.scalaDescriptor.messages(1)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = integration.framework.openlaw.MarkupInterfaceResponse(
    definition = ""
  )
  implicit class MarkupInterfaceResponseLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, integration.framework.openlaw.MarkupInterfaceResponse]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, integration.framework.openlaw.MarkupInterfaceResponse](_l) {
    def definition: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.definition)((c_, f_) => c_.copy(definition = f_))
  }
  final val DEFINITION_FIELD_NUMBER = 1
  def of(
    definition: _root_.scala.Predef.String
  ): _root_.integration.framework.openlaw.MarkupInterfaceResponse = _root_.integration.framework.openlaw.MarkupInterfaceResponse(
    definition
  )
}
