// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package integration.framework.openlaw

object SignatureCallbackServiceProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    integration.framework.openlaw.ExternalServiceProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      integration.framework.openlaw.SignatureCallbackResponse
    )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Ch5TaWduYXR1cmVDYWxsYmFja1NlcnZpY2UucHJvdG8SHWludGVncmF0aW9uLmZyYW1ld29yay5vcGVubGF3GhVFeHRlcm5hb
  FNlcnZpY2UucHJvdG8i3AEKGVNpZ25hdHVyZUNhbGxiYWNrUmVzcG9uc2USNQoMZXJyb3JNZXNzYWdlGAEgASgJQhHiPw4SDGVyc
  m9yTWVzc2FnZVIMZXJyb3JNZXNzYWdlEmQKBnN0YXR1cxgCIAEoDjI/LmludGVncmF0aW9uLmZyYW1ld29yay5vcGVubGF3LlNpZ
  25hdHVyZUNhbGxiYWNrUmVzcG9uc2UuU3RhdHVzQgviPwgSBnN0YXR1c1IGc3RhdHVzIiIKBlN0YXR1cxILCgdGQUlMVVJFEAASC
  woHU1VDQ0VTUxABMpIBChhTaWduYXR1cmVDYWxsYmFja1NlcnZpY2USdgoIQ2FsbGJhY2sSLi5pbnRlZ3JhdGlvbi5mcmFtZXdvc
  msub3Blbmxhdy5FeGVjdXRlUmVzcG9uc2UaOC5pbnRlZ3JhdGlvbi5mcmFtZXdvcmsub3Blbmxhdy5TaWduYXR1cmVDYWxsYmFja
  1Jlc3BvbnNlIgBiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
      integration.framework.openlaw.ExternalServiceProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}