// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package grpc.health.v1

@SerialVersionUID(0L)
final case class HealthCheckResponse(
    status: grpc.health.v1.HealthCheckResponse.ServingStatus = grpc.health.v1.HealthCheckResponse.ServingStatus.UNKNOWN
    ) extends scalapb.GeneratedMessage with scalapb.Message[HealthCheckResponse] with scalapb.lenses.Updatable[HealthCheckResponse] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = status
        if (__value != grpc.health.v1.HealthCheckResponse.ServingStatus.UNKNOWN) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(1, __value.value)
        }
      };
      __size
    }
    final override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = status
        if (__v != grpc.health.v1.HealthCheckResponse.ServingStatus.UNKNOWN) {
          _output__.writeEnum(1, __v.value)
        }
      };
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): grpc.health.v1.HealthCheckResponse = {
      var __status = this.status
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 8 =>
            __status = grpc.health.v1.HealthCheckResponse.ServingStatus.fromValue(_input__.readEnum())
          case tag => _input__.skipField(tag)
        }
      }
      grpc.health.v1.HealthCheckResponse(
          status = __status
      )
    }
    def withStatus(__v: grpc.health.v1.HealthCheckResponse.ServingStatus): HealthCheckResponse = copy(status = __v)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = status.javaValueDescriptor
          if (__t.getNumber() != 0) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PEnum(status.scalaValueDescriptor)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = grpc.health.v1.HealthCheckResponse
}

object HealthCheckResponse extends scalapb.GeneratedMessageCompanion[grpc.health.v1.HealthCheckResponse] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[grpc.health.v1.HealthCheckResponse] = this
  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, _root_.scala.Any]): grpc.health.v1.HealthCheckResponse = {
    _root_.scala.Predef.require(__fieldsMap.keys.forall(_.getContainingType() == javaDescriptor), "FieldDescriptor does not match message type.")
    val __fields = javaDescriptor.getFields
    grpc.health.v1.HealthCheckResponse(
      grpc.health.v1.HealthCheckResponse.ServingStatus.fromValue(__fieldsMap.getOrElse(__fields.get(0), grpc.health.v1.HealthCheckResponse.ServingStatus.UNKNOWN.javaValueDescriptor).asInstanceOf[_root_.com.google.protobuf.Descriptors.EnumValueDescriptor].getNumber)
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[grpc.health.v1.HealthCheckResponse] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      grpc.health.v1.HealthCheckResponse(
        grpc.health.v1.HealthCheckResponse.ServingStatus.fromValue(__fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor]).getOrElse(grpc.health.v1.HealthCheckResponse.ServingStatus.UNKNOWN.scalaValueDescriptor).number)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = HealthCheckProto.javaDescriptor.getMessageTypes.get(1)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = HealthCheckProto.scalaDescriptor.messages(1)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = {
    (__fieldNumber: @_root_.scala.unchecked) match {
      case 1 => grpc.health.v1.HealthCheckResponse.ServingStatus
    }
  }
  lazy val defaultInstance = grpc.health.v1.HealthCheckResponse(
    status = grpc.health.v1.HealthCheckResponse.ServingStatus.UNKNOWN
  )
  sealed trait ServingStatus extends _root_.scalapb.GeneratedEnum {
    type EnumType = ServingStatus
    def isUnknown: _root_.scala.Boolean = false
    def isServing: _root_.scala.Boolean = false
    def isNotServing: _root_.scala.Boolean = false
    def companion: _root_.scalapb.GeneratedEnumCompanion[ServingStatus] = grpc.health.v1.HealthCheckResponse.ServingStatus
  }
  
  object ServingStatus extends _root_.scalapb.GeneratedEnumCompanion[ServingStatus] {
    implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[ServingStatus] = this
    @SerialVersionUID(0L)
    case object UNKNOWN extends ServingStatus {
      val value = 0
      val index = 0
      val name = "UNKNOWN"
      override def isUnknown: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object SERVING extends ServingStatus {
      val value = 1
      val index = 1
      val name = "SERVING"
      override def isServing: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object NOT_SERVING extends ServingStatus {
      val value = 2
      val index = 2
      val name = "NOT_SERVING"
      override def isNotServing: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    final case class Unrecognized(value: _root_.scala.Int) extends ServingStatus with _root_.scalapb.UnrecognizedEnum
    
    lazy val values = scala.collection.immutable.Seq(UNKNOWN, SERVING, NOT_SERVING)
    def fromValue(value: _root_.scala.Int): ServingStatus = value match {
      case 0 => UNKNOWN
      case 1 => SERVING
      case 2 => NOT_SERVING
      case __other => Unrecognized(__other)
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = grpc.health.v1.HealthCheckResponse.javaDescriptor.getEnumTypes.get(0)
    def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = grpc.health.v1.HealthCheckResponse.scalaDescriptor.enums(0)
  }
  implicit class HealthCheckResponseLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, grpc.health.v1.HealthCheckResponse]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, grpc.health.v1.HealthCheckResponse](_l) {
    def status: _root_.scalapb.lenses.Lens[UpperPB, grpc.health.v1.HealthCheckResponse.ServingStatus] = field(_.status)((c_, f_) => c_.copy(status = f_))
  }
  final val STATUS_FIELD_NUMBER = 1
  def of(
    status: grpc.health.v1.HealthCheckResponse.ServingStatus
  ): _root_.grpc.health.v1.HealthCheckResponse = _root_.grpc.health.v1.HealthCheckResponse(
    status
  )
}
