// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package grpc.health.v1

object HealthCheckProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      grpc.health.v1.HealthCheckRequest,
      grpc.health.v1.HealthCheckResponse
    )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """ChFIZWFsdGhDaGVjay5wcm90bxIOZ3JwYy5oZWFsdGgudjEiPAoSSGVhbHRoQ2hlY2tSZXF1ZXN0EiYKB3NlcnZpY2UYASABK
  AlCDOI/CRIHc2VydmljZVIHc2VydmljZSKpAQoTSGVhbHRoQ2hlY2tSZXNwb25zZRJWCgZzdGF0dXMYASABKA4yMS5ncnBjLmhlY
  Wx0aC52MS5IZWFsdGhDaGVja1Jlc3BvbnNlLlNlcnZpbmdTdGF0dXNCC+I/CBIGc3RhdHVzUgZzdGF0dXMiOgoNU2VydmluZ1N0Y
  XR1cxILCgdVTktOT1dOEAASCwoHU0VSVklORxABEg8KC05PVF9TRVJWSU5HEAIyWgoGSGVhbHRoElAKBUNoZWNrEiIuZ3JwYy5oZ
  WFsdGgudjEuSGVhbHRoQ2hlY2tSZXF1ZXN0GiMuZ3JwYy5oZWFsdGgudjEuSGVhbHRoQ2hlY2tSZXNwb25zZWIGcHJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}